import assert from "node:assert/strict";
import { toBackendStatus, toFrontendStatus, mapVisit } from "../src/api/adapters";
import { createVesselVisit, getVesselVisits, cancelVesselVisit, editVesselVisit } from "../src/api/vesselApi";
import { getReadings } from "../src/api/readingApi";
import { getBerths } from "../src/api/berthApi";
import { getPredictions } from "../src/api/predictionApi";
import { apiFetch } from "../src/api/client";
import * as workflow from "../src/api/workflowApi";
import { convertToTph, convertFromTph } from "../src/lib/units";

const id = "76b543cc-bf36-4f4f-98e4-42b20205d15b";
const vessel = {id:"975eae6c-4471-49a0-a62f-0deb75078439", name:"Test ship", imo_reference:"TEST", created_at:"2026-09-02T00:00:00Z"};
const visit = {id, vessel_id:vessel.id, berth_id:"38d8ae8b-1557-4ace-b383-3105b29a1964", cargo_type:"Cement", cargo_total_t:"12500.00", status:"UNLOADING", planned_arrival:"2026-09-02T00:00:00Z", planned_unload_start:"2026-09-02T01:00:00Z", planned_completion:"2026-09-03T00:00:00Z", planned_rate_tph:"475.00", created_at:"2026-09-01T00:00:00Z", post_unloading_minutes:45};
let requests: {url:string; body:any; method:string}[] = [];
globalThis.fetch = async (url, init) => {
  const path = String(url).replace("http://test/api/v1", "");
  const body = init?.body ? JSON.parse(String(init.body)) : undefined;
  requests.push({url:path, body, method:init?.method || "GET"});
  let output: any;
  if (path === "/workflow/site") return new Response(JSON.stringify({configured:true, berth_id:visit.berth_id, berth_label:"Mangapwani — Berth 1", vessels:[]}),{status:200});
  if (path.startsWith("/workflow/")) return new Response(JSON.stringify({tasks:[]}),{status:200});
  if (path === "/integration/visits") output = init?.method === "POST" ? {visit, vessel} : [{visit, vessel}];
  else if (path === `/integration/visits/${id}`) output = {visit, vessel};
  else if (path === `/integration/visits/${id}/status`) output = {visit:{...visit, status:body.status}, vessel};
  else if (path.startsWith("/berths?")) output = [{id:visit.berth_id, name:"Berth 1", status:"OCCUPIED"}];
  else if (path.startsWith("/upcoming-calls?")) output = [];
  else if (path === `/visits/${id}`) output = visit;
  else if (path.startsWith(`/visits/${id}/readings?`)) output = [
    {id:"r2", recorded_at:"2026-09-02T02:00:00Z", unloaded_t:"4950.00", observed_rate_tph:"475.00", source:"MANUAL"},
    {id:"r1", recorded_at:"2026-09-02T01:00:00Z", unloaded_t:"4475.00", observed_rate_tph:"475.00", source:"MANUAL"},
  ];
  else if (path === "/integration/predictions") output = {[id]:{unloaded_t:"4950", remaining_t:"7550", progress_pct:"39.60", effective_rate_tph:"475", estimated_unload_finish:null, expected_berth_release:null, data_quality:"STALE"}};
  else if (path === "/invalid") return new Response(JSON.stringify({error:{details:[{loc:["body","berth_id"], msg:"Invalid UUID"}]}}), {status:422});
  else throw new Error(`Unexpected request ${path}`);
  return new Response(JSON.stringify(output), {status:200});
};

assert.equal(toBackendStatus("Delayed"), "DELAYED");
assert.equal(toFrontendStatus("CANCELLED"), "Cancelled");
assert.equal(toBackendStatus("Berthed"), "BERTHED");
const mapped = mapVisit(visit as any, vessel as any);
assert.equal(mapped.id, id);
assert.equal(mapped.plannedRateTph, 475);
assert(mapped.plannedCompletion instanceof Date);
assert.equal((await getBerths())[0].id, visit.berth_id);
assert.equal((await getBerths())[0].name, "Mangapwani — Berth 1");
const readings = await getReadings(id);
assert.equal(readings[1].unloadedT, 4950);
assert.equal(readings[1].remainingT, 7550);
assert.equal((await getVesselVisits())[0].id, id);
requests = [];
const input = {name:"Test ship", reference:"TEST", cargo:"Cement", cargoTotalT:12500, berthId:visit.berth_id, status:"Planned" as const, plannedArrival:"2026-09-02T03:00", plannedUnloadStart:"2026-09-02T04:00", plannedCompletion:"2026-09-03T00:00", plannedRateTph:475};
await createVesselVisit(input);
assert.equal(requests.length, 1, "Registration must be atomic, not two separate POSTs");
assert.equal(requests[0].url, "/integration/visits");
assert.equal(requests[0].body.status, "PLANNED");
assert(requests[0].body.plannedArrival.endsWith("Z"));
await editVesselVisit(id, {...input, status:"Delayed"});
assert.equal(requests[1].body.status, "DELAYED");
assert.equal((await cancelVesselVisit(id))?.status, "Cancelled");
const forecast = (await getPredictions())[id];
assert.equal(forecast.progressPct, 39.6);
assert.equal(forecast.dataQuality, "stale");
assert.equal(forecast.etaAvailable, false);
assert.equal(convertToTph(convertFromTph(475, "tpm"), "tpm"), 475);
await assert.rejects(() => apiFetch("/invalid"), /body.berth_id: Invalid UUID/);
await createVesselVisit({...input, vesselId:vessel.id});
assert.equal(requests.at(-1)?.body.vesselId, vessel.id);
await workflow.addTemplates(id,"Recorder");
assert.equal(requests.at(-1)?.body.performed_by,"Recorder");
assert.equal(requests.at(-1)?.url,`/workflow/visits/${id}/tasks/templates`);
const taskInput: workflow.TaskInput = {performed_by:"Recorder",title:"Pilot",category:"PILOT",owner_name:null,due_at:null,completed_at:null,status:"NOT_STARTED",blocks_departure:false,reason:"",evidence_reference:""};
await workflow.saveTask(id,taskInput);
assert.equal(requests.at(-1)?.method,"POST");
await workflow.saveTask(id,taskInput,{id:"task-1",version:3} as workflow.Task,"Reassign");
assert.equal(requests.at(-1)?.method,"PUT");
assert.equal(requests.at(-1)?.body.expected_version,3);
assert.equal(requests.at(-1)?.body.change_reason,"Reassign");
console.log("PASS: UUID/status/plan mappings, real berths, chronological readings, atomic create, edit/cancel, predictions, units, validation errors.");
